version: '2'

networks:
  lb_web:
    external: true
  back:
    driver: bridge

services:

  db:
    image: mariadb:latest
    volumes:
      - ./mysql/runtime2:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
    logging:
      driver: "json-file"
  
  app:
    image: matomo:fpm
    links:
      - db
    volumes:
      - ./config:/var/www/html/config:rw
      - ./logs:/var/www/html/logs:rw
    logging:
      driver: "json-file"
  
  web:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST
    logging:
      driver: "json-file"
    ports:
      - "7777:80"
  
